-- Migration: 022_employee_salary_configs.sql
-- Task 1.3: Create employee salary configuration table
-- Ref: pre-planning/03-data-model-proposal.md#21-employee-salary-config

-- TODO: Implement
-- CREATE TABLE IF NOT EXISTS public.employee_salary_configs (
--     id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
--     employee_id UUID NOT NULL REFERENCES public.employees(id) ON DELETE CASCADE,
--     
--     -- Fixed allowances (monthly)
--     position_allowance INTEGER DEFAULT 0,
--     additional_allowance INTEGER DEFAULT 0,
--     quota_allowance INTEGER DEFAULT 0,
--     education_allowance INTEGER DEFAULT 0,
--     transport_meal_allowance INTEGER DEFAULT 0,
--     bpjs_company_contribution INTEGER DEFAULT 0,
--     
--     -- Effective period
--     effective_from DATE NOT NULL DEFAULT CURRENT_DATE,
--     effective_to DATE,
--     
--     -- Audit
--     created_at TIMESTAMPTZ DEFAULT now(),
--     created_by UUID REFERENCES public.employees(id),
--     updated_at TIMESTAMPTZ DEFAULT now(),
--     
--     CONSTRAINT valid_effective_period CHECK (effective_to IS NULL OR effective_to >= effective_from)
-- );

-- CREATE INDEX idx_employee_salary_configs_employee ON public.employee_salary_configs(employee_id);

-- RLS Policies
-- ALTER TABLE public.employee_salary_configs ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "Admins can manage salary configs" ON public.employee_salary_configs FOR ALL USING (...);
-- CREATE POLICY "Employees can view own salary config" ON public.employee_salary_configs FOR SELECT USING (employee_id = auth.uid());
